name: Hello World Demo

on:
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.x'
        

      - name: Print Hello
        run: echo "🎉 Hello, GitHub Actions!"


      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pytest flake8

      - name: Run lint check
        run: flake8 app tests --max-line-length=100
        
      - name: Run tests
        run: pytest -v tests
